# Generated by Django 3.1.4 on 2020-12-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20201225_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='survey_id',
            new_name='survey',
        ),
    ]
