# Generated by Django 3.1.4 on 2020-12-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20201226_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='options',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
